# Generated by Django 3.0.5 on 2022-02-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='look!', max_length=255),
        ),
    ]
