# Generated by Django 3.0.5 on 2022-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lblog', '0003_auto_20220222_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
