# Generated by Django 3.0.5 on 2022-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lblog', '0006_auto_20220224_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Post snippet', max_length=255),
        ),
    ]
